FROM python:3.11-slim

WORKDIR /app

COPY . /app

# RUN apt-get update && apt-get install -y \
#     build-essential \
#     gcc \
#     libffi-dev \
#     libssl-dev \
#     libpq-dev \
#     libxml2-dev \
#     libxslt1-dev \
#     curl \
#     && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir -r requirements.txt

CMD ["celery", "-A", "app.celery_app.celery_app", "worker", "--loglevel=info"]